theme: jekyll-theme-merlot
title: Welcome to the BWRIGHT47's homepage!
description: Feel free to bookmark this page to keep an eye on my updates. I have added some basic calculation functions in seeing how pages of github works. :-)
